CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(30) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(30) NOT NULL,
    CUSTOMER_PW VARCHAR(30) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

INSERT INTO CUSTOMER (CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW) VALUES ("YOON", "ABCD@1234", "1234!@#$");