CREATE TABLE CUSTOMER(
    CUSTOMER_ID VARCHAR(255),
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    CUSTOMER_PW VARCHAR(255) NOT NULL,
    ACCOUNT_ID VARCHAR(255),
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE ACCOUNT(
    ACCOUNT_ID VARCHAR(255),
    ACCOUNT_NAME VARCHAR(255) NOT NULL,
    DEPOSIT BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (ACCOUNT_ID)
);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW) VALUES ("abcefdsger", "YOON", "ABCD@1234", "1234!@#$");