DROP TABLE CUSTOMER;
DROP TABLE ACCOUNT;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(255),
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    CUSTOMER_PW VARCHAR(255) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE ACCOUNT (
    ACCOUNT_ID VARCHAR(255),
    ACCOUNT_NAME VARCHAR(255) NOT NULL,
    DEPOSIT BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL
    PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE STOCK (
    CODE VARCHAR(255),
    STOCK_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE WATCHLIST (
    WATCH_ID VARCHAR(255),
    WATCH_INDEX BIGINT,
    STOCK_CODE VARCHAR(255) NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (WATCH_ID),
    FOREIGN KEY (STOCK_CODE) REFERENCES STOCK(STOCK_CODE),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);


INSERT INTO ACCOUNT(ACCOUNT_NAME, DEPOSIT) VALUES ("빨강이", 100000);
INSERT INTO ACCOUNT(ACCOUNT_NAME, DEPOSIT) VALUES ("파랭이", 300000);

INSERT INTO CUSTOMER(CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW, ACCOUNT_ID) VALUES ("김철수", "kim@example.com", "123456", 1);
INSERT INTO CUSTOMER(CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW, ACCOUNT_ID) VALUES ("강미나", "kang@example.com", "987654", 2);

INSERT INTO STOCK VALUES ("00135", "삼성전자");
INSERT INTO STOCK VALUES ("00138", "LG에너지솔루션");

INSERT INTO STOCK VALUES ("028260", "삼성물산");
INSERT INTO STOCK VALUES ("032830", "삼성생명");
INSERT INTO STOCK VALUES ("009150", "삼성전기");
INSERT INTO STOCK VALUES ("016360", "삼성증권");
INSERT INTO STOCK VALUES ("029780", "삼성카드");
INSERT INTO STOCK VALUES ("009155", "삼성전기우");
INSERT INTO STOCK VALUES ("005935", "삼성전자우");
INSERT INTO STOCK VALUES ("018260", "삼성에스디에스");
INSERT INTO STOCK VALUES ("207940", "삼성바이오로직스");


INSERT INTO STOCK VALUES ("066570", "LG전자");
INSERT INTO STOCK VALUES ("051910", "LG화학");
INSERT INTO STOCK VALUES ("011070", "LG이노텍");
INSERT INTO STOCK VALUES ("051900", "LG생활건강");
INSERT INTO STOCK VALUES ("032640", "LG유플러스");

INSERT INTO STOCK VALUES ("259960", "크래프톤");
INSERT INTO STOCK VALUES ("005380", "현대차");
INSERT INTO STOCK VALUES ("102280", "쌍방울");
INSERT INTO STOCK VALUES ("016790", "현대사료");

