DROP TABLE CUSTOMER;
DROP TABLE ACCOUNT;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(255),
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    CUSTOMER_PW VARCHAR(255) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);


CREATE TABLE ACCOUNT (
    ACCOUNT_ID VARCHAR(255),
    ACCOUNT_NAME VARCHAR(255) NOT NULL,
    DEPOSIT BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL
    PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE STOCK (
    STOCK_ID VARCHAR(255),
    STOCK_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (STOCK_ID)
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ACCOUNT
FOREIGN KEY (ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);


INSERT INTO ACCOUNT(ACCOUNT_NAME, DEPOSIT) VALUES ("빨강이", 100000);
INSERT INTO ACCOUNT(ACCOUNT_NAME, DEPOSIT) VALUES ("파랭이", 300000);

INSERT INTO CUSTOMER(CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW, ACCOUNT_ID) VALUES ("김철수", "kim@example.com", "123456", 1);
INSERT INTO CUSTOMER(CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PW, ACCOUNT_ID) VALUES ("강미나", "kang@example.com", "987654", 2);

INSERT INTO STOCK VALUES ("00135", "삼성전자");
INSERT INTO STOCK VALUES ("00138", "LG엔솔");
